'use client';
import { useLanguageContext } from '@/context/LanguageContext';

export type Lang = 'tr' | 'en';

/**
 * Kullanıcının seçtiği arayüz dilini döner.
 */
export function useLanguage(): Lang {
  const { lang } = useLanguageContext();
  return lang;
}

// ─── UI metin sabitleri ───────────────────────────────────────────────────────
export const UI_TEXT = {
  tr: {
    // Shared
    startLesson: 'Derse Başla 🔥',
    checkAnswer: 'Cevapla ✓',
    backToMap: '← Haritaya Dön',
    lessonDone: 'Ders Bitti!',
    tryAgain: 'Tekrar Dene 🔄',
    correct: 'Doğru! Bravo! 🎉',
    wrong: 'Yanlış, tekrar dene 💀',
    loading: 'Yükleniyor...',
    yourAnswer: 'Cevabını yaz...',
    hint: 'İpucu',
    proContent: 'PRO İçerik ⚡',
    completed: '✓ Tamamlandı',
    correctAnswer: 'Doğru cevap:',
    next: 'İleri →',
    finish: 'Bitir 🎉',
    lessonNotFound: 'Ders bulunamadı. Jebiga 💀',
    xpEarned: 'bu derste kazanıldı',
    mistakesMade: 'Sadece {n} hata yaptın.',
    generalProgress: 'Genel İlerleme',
    lessons: 'ders',
    chooseAnswer: '🧠 Cevabı Seç',
    translate: '✍️ Çevir',
    typeHere: 'Pişi ovde, brate...',
    correctAnswerFeedback: 'Mükemmel! Doğru cevap!',
    retry: 'TEKRAR',
    start: 'BAŞLA →',
    learningPath: 'Öğrenme Yolu',
    streetDictionary: 'Ulični Rečnik',
    learningDesc: 'Kategorileri aç, dersleri tamamla, XP kazan. Atlarsan jebiga!',
    streetDesc: 'Pazi, brate — svaka lekcija te bliže vodi pravom srpskom.',
    learn: 'ÖĞREN',
    profile: 'PROFİL',
    pro: 'PRO',
    profileTitle: 'Senin Profilin',
    levelLabel: 'Seviye',
    streakLabel: 'Seri',
    completedLabel: 'Bitti',
    sectionProgress: 'Bölümlere göre ilerlemen',
    upgradeToPro: "Jebiga Pro'ya Geç",
    upgradeDesc: 'Yapay Zeka botu, daha fazla küfür, sokak jargonu ve fazlasıyla.',
    becomePro: 'Pro Ol ⚡',
    interfaceLanguage: '🌐 Arayüz Dili',
    interfaceDescTr: 'Dersler ve arayüz Türkçe gösterilir',
    interfaceDescEn: 'Lessons and UI are shown in English',
    logout: 'Çıkış Yap 🚪',
    salesClosed: 'Şuan alımlar kapalı, en yakın zamanda açılacaktır!',
    purchasesDisabled: 'SATIN ALIMLAR KAPALI 🔒',
    botTitle: 'Kafana Dayısı',
    botSubtitle: '⚡ PRO SOKAK HOCASI',
    botGreeting: "Ooo brate, hoćeš da öğrenesin pravu Sırpçayı? Kafana dayısına sor bakalım! Ne içiyoruz? 🥃",
    botThinking: 'Dayı düşünüyor...',
    botPlaceholder: "Dayı'ya bir şey sor...",
    botSend: 'At',
    botError: 'Brate, internet gitti jebiga!',
    startQuiz: '🚀 Teste Başla',
    
    // Landing Page
    heroTitle: 'Sırpçayı Sokak Ağzıyla Öğren.',
    heroSubtitle1: 'Ders kitabı değil, kafana argolarıyla öğren.',
    heroSubtitle2: 'Duolingo’dan farklı — çok daha havalı, çok daha gerçek.',
    login: 'Giriş Yap',
    signup: 'Kayıt Ol',
    getStarted: 'Başla →',
    learnSerbian: 'Sırpça Öğren',
    firstAppBadge: "⚡ Türkiye'nin İlk Sırpça Sokak Modu Uygulaması",
    freeStart: '🚀 Ücretsiz Başla',
    howItWorks: 'Nasıl Çalışır? ↓',
    whyJebiga: 'Neden Jebiga?',
    threeStepsTitle: 'Üç adımda Sırpça',
    step1Title: 'Konu Anlatımı',
    step1Desc: 'Her ders senaryoyla başlar. Kelime, diyalog, kültür ipuçları — hiçbir şey eksik değil.',
    step2Title: 'Sorularla Pekiştir',
    step2Desc: 'Çoktan seçmeli, çeviri, boşluk doldurma. Öğrendiklerini hemen test edersin.',
    step3Title: 'XP Kazan, İlerle',
    step3Desc: 'Her derste XP kazanırsın. Seri tutarsın. Sonraki kategoriler açılır. Dur yok.',
    testimonialsTitle: 'Onlar ne dedi?',
    readyBrate: 'Hazır mısın, brate?',
    registerNow: 'Hemen Kaydol — Ücretsiz 🚀',
    noCardRequired: 'Kredi kartı gerekmez. 5 saniyede kaydol.',
    footerDesc: 'Sırpçayı sokak ağzıyla öğren.',
  },
  en: {
    // Shared
    startLesson: 'Start Lesson 🔥',
    checkAnswer: 'Check ✓',
    backToMap: '← Back to Map',
    lessonDone: 'Lesson Complete!',
    tryAgain: 'Try Again 🔄',
    correct: 'Correct! Well done! 🎉',
    wrong: 'Wrong, try again 💀',
    loading: 'Loading...',
    yourAnswer: 'Type your answer...',
    hint: 'Hint',
    proContent: 'PRO Content ⚡',
    completed: '✓ Completed',
    correctAnswer: 'Correct answer:',
    next: 'Next →',
    finish: 'Finish 🎉',
    lessonNotFound: 'Lesson not found. Jebiga 💀',
    xpEarned: 'earned in this lesson',
    mistakesMade: 'You only made {n} mistake(s).',
    generalProgress: 'General Progress',
    lessons: 'lessons',
    chooseAnswer: '🧠 Choose Answer',
    translate: '✍️ Translate',
    typeHere: 'Type here, brate...',
    correctAnswerFeedback: 'Excellent! Correct answer!',
    retry: 'RETRY',
    start: 'START →',
    learningPath: 'Learning Path',
    streetDictionary: 'Street Dictionary',
    learningDesc: 'Open categories, finish lessons, earn XP. If you skip, jebiga!',
    streetDesc: 'Pazi, brate — every lesson takes you closer to real Serbian.',
    learn: 'LEARN',
    profile: 'PROFILE',
    pro: 'PRO',
    profileTitle: 'Your Profile',
    levelLabel: 'Level',
    streakLabel: 'Streak',
    completedLabel: 'Done',
    sectionProgress: 'Your progress by section',
    upgradeToPro: 'Upgrade to Jebiga Pro',
    upgradeDesc: 'AI Bot, more swearing, street slang, and more.',
    becomePro: 'Go Pro ⚡',
    interfaceLanguage: '🌐 Interface Language',
    interfaceDescTr: 'Lessons and UI are shown in Turkish',
    interfaceDescEn: 'Lessons and UI are shown in English',
    logout: 'Logout 🚪',
    salesClosed: 'Currently purchases are closed, will be available soon!',
    purchasesDisabled: 'PURCHASES DISABLED 🔒',
    botTitle: 'Kafana Uncle',
    botSubtitle: '⚡ PRO STREET TEACHER',
    botGreeting: "Ooo brate, you want to learn real Serbian? Ask Kafana Uncle! What are we drinking? 🥃",
    botThinking: 'Uncle is thinking...',
    botPlaceholder: 'Ask Uncle something...',
    botSend: 'Send',
    botError: 'Brate, the internet is gone jebiga!',
    startQuiz: '🚀 Start Quiz',

    // Landing Page
    heroTitle: 'Learn Serbian the Street Way.',
    heroSubtitle1: 'Not a textbook, learn with real kafana slang.',
    heroSubtitle2: "Different from Duolingo — much cooler, much more real.",
    login: 'Login',
    signup: 'Sign Up',
    getStarted: 'Get Started →',
    learnSerbian: 'Learn Serbian',
    firstAppBadge: "⚡ Turkey's First Serbian Street Mode App",
    freeStart: '🚀 Start for Free',
    howItWorks: 'How it Works? ↓',
    whyJebiga: 'Why Jebiga?',
    threeStepsTitle: 'Serbian in Three Steps',
    step1Title: 'Lesson Content',
    step1Desc: 'Every lesson starts with a scenario. Vocabulary, dialogue, cultural tips — nothing is missing.',
    step2Title: 'Reinforce with Quiz',
    step2Desc: 'Multiple choice, translation, fill in the blanks. Test what you learn instantly.',
    step3Title: 'Earn XP, Advance',
    step3Desc: 'Earn XP in every lesson. Keep your streak. Unlock the next categories. No stopping.',
    testimonialsTitle: 'What they said?',
    readyBrate: 'Are you ready, brate?',
    registerNow: 'Register Now — Free 🚀',
    noCardRequired: 'No credit card required. Register in 5 seconds.',
    footerDesc: 'Learn Serbian the street way.',
  },
} as const;
